# Generated by Django 3.0 on 2019-12-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('perdido_encontrado', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=75)),
                ('numero_de_telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_desaparecido', models.DateField(blank=True, null=True)),
                ('fecha_encontrado', models.DateField(blank=True, null=True)),
                ('pais', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('barrio', models.CharField(max_length=50)),
                ('info_extra', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
